; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6812EA7A-2FF7-48D0-BEAF-0E8C1528F7B1}
AppName=Console Launcher
AppVersion=1.4
;AppVerName=Console Launcher 1.3
AppPublisher=JMBA Softwares
AppPublisherURL=http://consolelauncher.blogspot.com
AppSupportURL=http://consolelauncher.blogspot.com
AppUpdatesURL=http://consolelauncher.blogspot.com
DefaultDirName=C:\JMBA Softwares\Console Launcher
DisableProgramGroupPage=yes
OutputDir=C:\Users\Phobos\Desktop
OutputBaseFilename=Clauncher_Setup1.4
SetupIconFile=D:\Phobos\Pessoal\Google Drive\DEVS\Console_Launcher\01 - Material\Images\setup.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "D:\Phobos\Pessoal\Google Drive\DEVS\Console_Launcher\Modulo de Instalação\CLauncher.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Phobos\Pessoal\Google Drive\DEVS\Console_Launcher\Modulo de Instalação\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Console Launcher"; Filename: "{app}\CLauncher.exe"
Name: "{commondesktop}\Console Launcher"; Filename: "{app}\CLauncher.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Console Launcher"; Filename: "{app}\CLauncher.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\CLauncher.exe"; Description: "{cm:LaunchProgram,Console Launcher}"; Flags: nowait postinstall skipifsilent

